
IG_API_KEY = "2ccd329c3d24c2d87e8b0dc0cd977bd4e6267663"
HTX_API_KEY = "<KEY>"
HTX_API_SECRET = "<KEY>"

BINANCE_API_KEY = "<KEY>"
BINANCE_API_SECRET = "<KEY>"

MEXC_API_KEY = "<KEY>"
MEXC_API_SECRET = "<KEY>"

OKX_API_KEY = "<KEY>"
OKX_API_SECRET = "<KEY>"